Repository Team-S5T1/weasel-backend, pull requests merged in 2024-08, with the labels that each got.

#22 ci: ci pipeline enhancement
  Jenkinsfile
Labels: 🎉 enhancement

#24 feat: History, Prompt 컨트롤러 생성
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/dto/HistoryDTO.java
  app/src/main/java/exam/master/dto/MemberDTO.java
  app/src/main/java/exam/master/dto/PromptDTO.java
  app/src/main/java/exam/master/repository/HistoryRepository.java
  app/src/main/java/exam/master/repository/PromptRepository.java
  app/src/main/java/exam/master/service/HistoryService.java
  app/src/main/java/exam/master/service/MemberService.java
  app/src/main/java/exam/master/service/PromptService.java
  app/src/test/java/exam/master/service/MemberServiceTest.java
  app/src/test/java/exam/master/service/PromptServiceTest.java
Labels: 🔥 feature

#29 chore: gitignore 파일에서 *.yml 수정
  .gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/java/exam/master/service/HistoryService.java
  app/src/main/resources/application.yml
  app/src/test/resources/application.yml
Labels: 🔥 feature

#35 feat: bedrock 연동, addPrompt() 수정
  .gitignore
  app/build.gradle
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/config/InvokeModel.java
  app/src/main/java/exam/master/service/PromptService.java
  app/src/test/resources/application.yml
Labels: 🔥 feature

#38 refactor: 컨트롤러에서 loginMember으로 네이밍 변경
  app/build.gradle
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/api/MemberApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/dto/LogInRequest.java
  app/src/main/java/exam/master/dto/LoginResponse.java
  app/src/main/java/exam/master/repository/MemberRepository.java
  app/src/main/java/exam/master/service/MemberService.java
  app/src/main/java/exam/master/service/PromptService.java
  app/src/main/java/exam/master/session/SessionConst.java
Labels: 🔥 feature

#41 Feat/#26 link bedrock and s3
  .idea/compiler.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/modules.xml
  .idea/modules/app/exam-master.app.test.iml
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/config/InvokeModel.java
  app/src/main/java/exam/master/service/HistoryService.java
  app/src/main/java/exam/master/service/MemberService.java
  app/src/main/java/exam/master/service/PromptService.java
  app/src/test/java/exam/master/InvokeTest.java
  app/src/test/java/exam/master/service/MemberServiceTest.java
  app/src/test/resources/chemistry_problem.png
  app/src/test/resources/problem 1.png
Labels: 🔥 feature

#52 fix: 회원가입 시 회원가입 성공 여부 확인
  app/src/main/java/exam/master/api/MemberApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/dto/JoinResponse.java
  app/src/main/java/exam/master/service/MemberService.java
  app/src/main/resources/application.yml
Labels: 🚨 bug

#54 refactor: cors 설정 수정
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/api/MemberApiController.java
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/service/MemberService.java
  app/src/main/java/exam/master/service/PromptService.java
Labels: 🔥 feature

#55 fix: answer 컬럼 크기 수정
  app/src/main/java/exam/master/api/PromptApiController.java
  app/src/main/java/exam/master/config/InvokeModel.java
  app/src/main/java/exam/master/domain/Prompt.java
  app/src/main/java/exam/master/service/PromptService.java
Labels: 🚨 bug

#58 feat: add prompt engineering
  app/src/main/java/exam/master/config/InvokeModel.java
Labels: 🔥 feature

#60 fix: 히스토리 삭제 및 베드락 프롬프트 버그 수정
  app/src/main/java/exam/master/api/HistoryApiController.java
  app/src/main/java/exam/master/config/InvokeModel.java
  app/src/main/java/exam/master/service/HistoryService.java
Labels: 🚨 bug

#63 feat: Spring Security 적용
  .idea/modules.xml
  .idea/modules/app/exam-master.app.main.iml
  app/build.gradle
  app/src/main/java/exam/master/api/MemberApiController.java
  app/src/main/java/exam/master/repository/HistoryRepository.java
  app/src/main/java/exam/master/security/MemberUserDetails.java
  app/src/main/java/exam/master/security/MyUserDetailsService.java
  app/src/main/java/exam/master/security/SecurityConfig.java
  app/src/main/java/exam/master/service/MemberService.java
Labels: 🔥 feature

#66 refactor: 프로필 사진 이름 변경 코드 수정
  app/src/main/java/exam/master/service/MemberService.java
Labels: 🚨 bug

#67 refactor: 비밀번호 업데이트 코드 수정
  app/src/main/java/exam/master/api/MemberApiController.java
Labels: 🚨 bug

#70 feat: 소셜 로그인
  app/build.gradle
  app/src/main/java/exam/master/api/socialLoginApiController.java
  app/src/main/java/exam/master/domain/Member.java
  app/src/main/java/exam/master/repository/MemberRepository.java
  app/src/main/java/exam/master/security/CustomOAuth2UserService.java
  app/src/main/java/exam/master/security/MemberUserDetails.java
  app/src/main/java/exam/master/security/MyUserDetailsService.java
  app/src/main/java/exam/master/security/Provider.java
  app/src/main/java/exam/master/security/SecurityConfig.java
  app/src/main/resources/application.yml
  app/src/test/resources/application.yml
Labels: 🔥 feature

#69 enhancement: prompt and top_p, top_k update
  app/src/main/java/exam/master/config/InvokeModel.java
Labels: 🎉 enhancement
